apiVersion: v1
kind: Service
metadata:
  name: service-servicea-clusterip
spec:
  type: ClusterIP
  selector:
    app: service-a
  ports:
    - port: 7002
      targetPort: 7002

# kubectl apply -f service_a_service.yaml
# kubectl get svc
# kubectl get endpoints
# kubectl run -it --rm --image=busybox dns-test -- nslookup service-servicea-clusterip.svc.cluster.local
